harulog/config/routes.rb
Harulog::Application.routes.draw do

  resources :users
  match '/contact', :to => 'pages#contact'
  match '/signup' , :to => 'users#new'
  match '/about'  , :to => 'pages#about'

  root :to => 'pages#home'  

end

harulog/app/models/user.rb
class User < ActiveRecord::Base

  # accessors
  attr_accessor :password
 
  # public attributes
  attr_accessible :name, :email, :password, :password_confirmation

  # regular expression to check email format
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  #validations
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }

  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => true

  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
 

  # before saving to the DB
  before_save :encrypt_password

  # 
  # Method : has_password?
  # 
  # Returns TRUE if the encrypted form of input password
  # matches the stored encrypted password.
  #
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  #
  # Method : authenticate
  #
  # Returns the user corresponding to the input email only
  # if the given password is correct.  Returns Null otherwise.
  #
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

    #
    # Function : encrypt_password
    #
    # Creates a salt and also a password for user.
    # Used before storing the password in DB
    #
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    #
    # Function : encrypt
    #
    # Returns an encrypted form of the input string using
    # the current user's salt
    #
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    #
    # Function : make_salt
    #
    # Returns a salt value
    #
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    #
    # Function : secure_hash
    #
    # Returns an encrypted input string using SHA2
    #
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
   
end

harulog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

harulog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
  end

  def setting
  end

  def logout
  end

  def about
  end

end

harulog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Signup"
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      # Handle a successful save.
      flash[:success] = "Wassup yo"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
end

harulog/app/helpers/application_helper.rb
module ApplicationHelper
end

harulog/app/helpers/pages_helper.rb
module PagesHelper
end

harulog/app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>


harulog/app/views/layouts/_header.html.erb
<header>
  <%= image_tag("logo.png", :alt => "Harulog", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", '#' %></li>
      <li><%= link_to "Profile", '#' %></li>
      <li><%= link_to "Settings", '#' %></li>
      <li><%= link_to "Logout", '#' %></li>
    </ul>
  </nav>
</header>

harulog/app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>


harulog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
   </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>      
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

harulog/app/views/pages/home.html.erb
<h1>HOME</h1>
<p>
  This is the main page
  <%= link_to "Sign up!", signup_path, :class => "signup_button round" %>
</p>

harulog/app/views/pages/logout.html.erb
<h1>Pages#logout</h1>
<p>Find me in app/views/pages/logout.html.erb</p>

harulog/app/views/pages/profile.html.erb
<h1>Pages#profile</h1>
<p>Find me in app/views/pages/profile.html.erb</p>

harulog/app/views/pages/setting.html.erb
<h1>Pages#setting</h1>
<p>Find me in app/views/pages/setting.html.erb</p>

harulog/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


harulog/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>


harulog/app/views/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>
